import React from "react";
import { Link } from "react-router-dom";

const values = [{ icon: "⌁", title: "Books for every reader", text: "From first stories to serious study, our shelves make room for every kind of curiosity." }, { icon: "₹", title: "Fair, clear pricing", text: "Straightforward prices help you spend less time comparing and more time reading." }, { icon: "→", title: "Simple from shelf to door", text: "A focused browsing and checkout experience keeps ordering pleasantly uncomplicated." }];

const About = () => <main className="bg-[#f7f6f2]">
  <section className="bg-slate-900 px-4 py-20 text-white sm:px-6 sm:py-28"><div className="mx-auto max-w-5xl text-center"><p className="text-xs font-bold uppercase tracking-[0.25em] text-orange-400">Our story</p><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-6xl">A bookstore built around curiosity.</h1><p className="mx-auto mt-6 max-w-2xl text-base leading-8 text-slate-300 sm:text-lg">We believe the right book can change a quiet afternoon, unlock a difficult subject, or open a completely new way of seeing the world.</p></div></section>
  <section className="px-4 py-14 sm:px-6 sm:py-20"><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-2"><div className="relative overflow-hidden rounded-3xl bg-orange-100 p-7 sm:p-10"><div className="grid grid-cols-3 items-end gap-3">{["📕", "📗", "📘"].map((book, index) => <div key={book} className={`flex items-center justify-center rounded-xl bg-white shadow-xl ${index === 1 ? "h-64 text-7xl" : "h-52 text-6xl"}`}>{book}</div>)}</div></div><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-orange-600">Why we’re here</p><h2 className="mt-3 text-3xl font-black text-slate-900 sm:text-4xl">Make finding a good book feel easy.</h2><p className="mt-5 leading-7 text-slate-600">BookStore brings stories and study materials into one welcoming place. Whether you are reading for joy, buying for a child, or preparing for a milestone exam, we want the path from discovery to delivery to feel clear.</p><p className="mt-4 leading-7 text-slate-600">This demo store is designed with a simple principle: let the books lead, keep the interface calm, and never put friction between a reader and their next page.</p></div></div></section>
  <section className="bg-white px-4 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-6xl"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[0.22em] text-orange-600">What matters to us</p><h2 className="mt-3 text-3xl font-black text-slate-900">Made for real reading lives</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{values.map((value) => <article key={value.title} className="rounded-2xl border border-slate-200 p-6"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-orange-50 text-xl font-black text-orange-600">{value.icon}</span><h3 className="mt-5 text-lg font-black text-slate-800">{value.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{value.text}</p></article>)}</div></div></section>
  <section className="px-4 py-16 sm:px-6"><div className="mx-auto max-w-5xl rounded-3xl bg-orange-500 px-6 py-12 text-center text-white sm:px-12"><h2 className="text-3xl font-black">Your next book is already here.</h2><p className="mt-3 text-orange-100">Take a look around. The right cover might surprise you.</p><Link to="/" className="mt-6 inline-block rounded-full bg-white px-6 py-3 text-sm font-bold text-orange-600 hover:bg-orange-50">Browse the shelves</Link></div></section>
</main>;

export default About;
